#!/bin/sh
# [Clauderizer] SessionStart wrapper — regenerated by `clauderize init`; do not edit.
# A session whose engine cannot launch must still learn why (H-01): any
# engine failure becomes a breadcrumb on STDOUT (the session context).
# engine-hook: /home/ccusce/.local/bin/uvx -q --from clauderizer clauderizer-hook
cd '/home/ccusce/clauderizer-site' 2>/dev/null || {
  printf '%s %s — run `clauderize doctor`\n' '[Clauderizer] repo unreachable:' '/home/ccusce/clauderizer-site'
  exit 0
}
out=$(/home/ccusce/.local/bin/uvx -q --from clauderizer clauderizer-hook "$@" 2>&1)
status=$?
if [ "$status" -eq 0 ]; then
  [ -n "$out" ] && printf '%s\n' "$out"
else
  printf '[Clauderizer] engine unreachable: exit %s from %s — run `clauderize doctor`\n%s\n' \
    "$status" "/home/ccusce/.local/bin/uvx" "$out"
fi
exit 0
